RevenuePayroll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.models import DowntimeTracker
from core.agent_view.agent_view import (AgentHomeView, ApproveDispute,RaiseDispute,PayrollView)
from core.finance_view.finnace_view import FinanceDashboardView, FinanceDisputeView, FinanaceAddressedDisputeView
from core.login_view.login_view import ChangePasswordView, LoginView, LogoutView
from core.supervisor_view.supervisor_view import (DowntimeProcessView, PayrollApprovedView, PayrollNotApprovedView, SupervisorDisputeView,DowntimeTrackerView,SupervisorView,AddAgentView,SupAcwView)

from core.om_view.om_view import OperationsDisputeView, OperationsManagerView,PasswordResetView,OmAddAgentView,DowntimeApprovalView, ProcessAutoDowntimeView,change_supervisor_lob,gen_report, UnattenedDisputeView, UnattenedPayrollView, OmAcwView
from core.utils.common import agent_payroll_view, ajax_get_client, save_email, sup_om_gen_report,approved_disputes
from core.views import maintenance

app_name = 'core'

urlpatterns = [

    # login urls
    path('',LoginView.as_view(),name='login'),
    # url(r'^',maintenance,name='login'),
    path('logout/',LogoutView,name='logout'),
    path('password/change/',ChangePasswordView.as_view(),name='change-password'),
    
    # agents urls
    path('agent/',login_required(AgentHomeView.as_view()),name='home'),
    path('agent/payroll/',PayrollView.as_view(),name='agent-payroll'),
    # dispute related agent urls
    path('agent/approve/',ApproveDispute,name='approve'),
    path('agent/dispute/',RaiseDispute,name='raise-dispute'),


    # operations manager urls
    path('operations/',login_required(OperationsManagerView.as_view()),name='operations'),
    path('operations/reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('operations/add/',OmAddAgentView.as_view(),name='add_agent'),
    path('operations/change_supervisor_lob/',login_required(change_supervisor_lob),name='change_supervisor_lob'),
    path('operations/downtime-approve/',DowntimeApprovalView.as_view(),name='downtime-approve'),
    path('operations/disputes/',OperationsDisputeView.as_view(),name='om-disputes'),
    path('operations/payroll/<pk>/',agent_payroll_view,name='agent_payroll'),
    path('operations/process/downtime/',ProcessAutoDowntimeView.as_view(),name='ops-process-downtime'),
    path('operations/unattended/disputes/',UnattenedDisputeView.as_view(),name='om-unattended-disputes'),
    path('operations/unattended/payrolls/',UnattenedPayrollView.as_view(),name='om-unattended-payrolls'),
    path('operations/acw/',OmAcwView.as_view(),name='om-acw'),
    # path('operations/approved/disputes/',approved_disputes,name='om-approved-disputes'),
    
    # supervisor urls
    path('supervisor/',login_required(SupervisorView.as_view()),name='super-home'),
    path('supervisor/add/',AddAgentView.as_view(),name='super_add_agent'),
    path('profile/',login_required(SupervisorView.as_view()),name='profile'),
    path('supervisor/downtime-tracker/',DowntimeTrackerView.as_view(),name='downtime-tracker'),
    path('supervisor/disputes/',SupervisorDisputeView.as_view(),name='super-disputes'),
    path('supervisor/payroll/<int:pk>/',agent_payroll_view,name='super_agent_payroll'),
    path('supervisor/process/downtime/',DowntimeProcessView.as_view(),name='process-downtime'),
    path('supervisor/payroll/approved/',PayrollApprovedView.as_view(),name='sup-approved-payroll'),
    path('supervisor/payroll/not/approved/',PayrollNotApprovedView.as_view(),name='sup-not-approved-payroll'),
    path('supervisor/acw/',SupAcwView.as_view(),name='super-acw'),
    # path('supervisor/approved/disputes/',approved_disputes,name='sup-approved-disputes'),

    # finacne urls
    path('finance/',FinanceDashboardView.as_view(),name='finance-index'),
    path('finance/disputes/',FinanceDisputeView.as_view(),name='finn-disputes'),
    path('finance/payroll/<pk>/',agent_payroll_view,name='finn_agent_payroll'),
    path('finance/addressed/disputes/',FinanaceAddressedDisputeView.as_view(),name='finn-addressed-dispute'),
    # path('finance/approved/disputes/',approved_disputes,name='finance-approved-disputes'),
    # report export path
    path('export/',gen_report,name='export'),
    path('export-csv/',sup_om_gen_report,name='export-csv'),

    path('save/email/',save_email,name='save-email'),
    path('get/ajax/client', ajax_get_client, name='get_ajax_client'),
]

templates/supervisor/agent_payroll_approve.html
{% extends 'new_base.html' %}
{% load static %}
{% load remove_dot %}


{% block title %}
    Approved Payroll Logs
{% endblock title %}
    

{% block content %}
    <!-- Main section-->
<section class="section-container">
    <!-- Page content-->
    <div class="content-wrapper">
       <div class="content-heading">
          <div>Payroll Approved Logs<small>Below table contains data of all those employees who have approved their payroll in last 3 days.</small></div>
       </div>
       <!-- DATATABLE DEMO 1-->
       <div class="card" style="width:max-content;">
          <div class="card-header">
             <div class="card-title">Payroll Approved Logs</div>
             <div class="text-sm"></div>
          </div>
          <div class="card-body" style="width: fit-content;">
             
             <div class="table bootgrid">
                <!-- custom table from the previous project -->
             <table class="table table-bordered table-hover" id="bootgrid-command" style="color: black;">
                <thead>
                   <tr role="row" style="background-color: rgba(0, 183, 255, 0.15);word-wrap: normal;">
                       <th rowspan="2" colspan="1" style="text-align: center;width: max-content;" >Payroll Generated Date
                       </th>
                       <th rowspan="2" colspan="1" style="text-align: center;" >Agent Name
                       </th>
                       <th rowspan="2"
                           colspan="1" style="text-align: center;" >Agent Approved On
                       </th>
                   </tr>
                   </thead>
                   <tbody>
                   <!--
                       For Performance Reasons Content will be served to data tables as JSON
                   -->
                   {% for item in approved_disputes_by_agents %}
                   <tr>
                       <td style="width: max-content;">{{item.dispute_date}}</td>
                       <td>{{item.employee|remove_dot}}</td>
                       <td>{{item.created_at}}</td>
                   </tr>
 
                   {% endfor %}
                   <tr class="odd">
                       <td valign="top" colspan="9" class="dataTables_empty"></td>
                   </tr>
                   </tbody>
             </table>
 
             {% if approved_disputes_by_agents.has_other_pages %}
             <ul class="pagination">
                 {% if approved_disputes_by_agents.has_previous %}
                 <li class="page-item">
                   <a class="page-link" href="?page=1" aria-label="Previous">
                     <span aria-hidden="true">&laquo;</span>
                     <span class="sr-only">begin</span>
                   </a>
                 </li>   {% endif %}
                 
                 {% for n in approved_disputes_by_agents.paginator.page_range %}
                   {% if approved_disputes_by_agents.number == n %}
                     <li class="page-item active">
                       <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                     </li>
                   {% elif n > approved_disputes_by_agents.number|add:'-3' and n < approved_disputes_by_agents.number|add:'3' %}
                     <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                   {% endif %}
                 {% endfor %}
                 
                 {% if approved_disputes_by_agents.has_next %}
                   <li class="page-item">
                     <a class="page-link" href="?page={{ approved_disputes_by_agents.paginator.num_pages }}" aria-label="Next">
                       <span aria-hidden="true">&raquo;</span>
                       <span class="sr-only">end</span>
                     </a>
                   </li>
                   {% endif %}
             </ul>
          {% endif %}
             </div>
             
          
          </div>
       </div>
       
    </div>
 </section>
{% endblock content %}
    

templates/supervisor/downtime_index.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
    Downtime Process Logs
{% endblock title %}
    

{% block content %}

<!-- Main section -->
<section class="section-container">
    <!-- Page content -->
    <div class="content-wrapper">
        <div>
            Downtime Tracker
            <small>
                Let's make the things simple by this tracker.
            </small>
        </div>
        <!-- DATATABLE DEMO -->
        <div class="card" style="width: max-width;">
            <div class="card-header">
                <div class="card-title">Agent's Downtime Logs</div>
                <div class="text-sm"></div>
            </div>
            <div class="card-body" style="width: max-width;">
                <div class="table bootgrid">
                    <!-- custom table from the previous project -->
                 <table class="table table-bordered table-hover" id="bootgrid-command" style="color: black;">
                    <thead>
                       <tr role="row" style="background-color: rgba(0, 183, 255, 0.15);word-wrap: normal;">
                           <th rowspan="2" colspan="1" style="text-align: center;width: max-content;" >Date
                           </th>
                           <th rowspan="2" colspan="1" style="text-align: center;" >Agent's Name
                           </th>
                           <th style="text-align: center;"
                               rowspan="2" colspan="1"
                               >Coaching (Hrs)
                           </th>
                           <th style="text-align: center;"
                               rowspan="2" colspan="1"
                               >Training (Hrs)
                           </th>
                           <th style="text-align: center;"
                               rowspan="1" colspan="2"
                               >Actions
                           </th>
                       </tr>
                       <tr style="background-color: rgba(0, 183, 255, 0.15);">
                           <th>Approve</th>
                           <th>Decline</th>
                       </tr>
                       </thead>
                       <tbody>
                       <!--
                           For Performance Reasons Content will be served to data tables as JSON
                       -->
                       {% for item in res %}
                           
                                
                       <tr>
                           <td style="width: max-content;">{{item.startdate}}</td>
                           <td>{{item.login_id|title}}</td>
                           <td>{{item.coaching_time}}</td>
                           <td>{{item.training_time}}</td>     
                           <td>
                               <form action="
                               {% if request.user.role == 'TEAM_SUP' %}
                                    {% url 'core:process-downtime' %}
                                {% else %}
                                    {% url 'core:ops-process-downtime' %}
                               {% endif %}
                               " method="post">
                                   {% csrf_token %}
                                   <input type="hidden" name="action" value="YES">
                                   <input type="hidden" name="trackerId" value="{{item.pk}}">
                                   <button type="submit" class="btn btn-success btn-sm" value="Approve" ><i class="far fa-calendar-check fa-2x"></i></button>
                               </form>
                           </td>
     
     
                           <td>
                            <form action="
                            {% if request.user.role == 'TEAM_SUP' %}
                                {% url 'core:process-downtime' %}
                            {% else %}
                                {% url 'core:ops-process-downtime' %}
                            {% endif %}" 
                            method="post">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="NO">
                                <input type="hidden" name="trackerId" value="{{item.pk}}">
                                <button type="submit" class="btn btn-danger btn-sm" value="Decline" ><i class="fas fa-fist-raised fa-2x"></i></button>
                            </form>
                           </td>     
                       </tr>
     
                       {% endfor %}
                       <tr class="odd">
                           <td valign="top" colspan="9" class="dataTables_empty"></td>
                       </tr>
                       </tbody>
                 </table>
     
                 {% if res.has_other_pages %}
                    <ul class="pagination">
                        {% if res.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">begin</span>
                          </a>
                        </li>   {% endif %}
                        
                        {% for n in res.paginator.page_range %}
                          {% if res.number == n %}
                            <li class="page-item active">
                              <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                            </li>
                          {% elif n > res.number|add:'-3' and n < res.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                          {% endif %}
                        {% endfor %}
                        
                        {% if res.has_next %}
                          <li class="page-item">
                            <a class="page-link" href="?page={{ res.paginator.num_pages }}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">end</span>
                            </a>
                          </li>
                          {% endif %}
                    </ul>
                 {% endif %}
                 
                 </div>
                 
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/supervisor/payroll-super.html
{% extends 'new_base.html' %}
{% load static %}


{% block title %}
{{title}}
{% endblock title %}


{% block content %}
<style>
   .modal-backdrop {
      /* bug fix - no overlay */
      display: none;
   }
</style>
<!-- Main section-->
<section class="section-container">
   <!-- Page content-->
   <div class="content-wrapper">
      <div class="content-heading">
         <div>Open Disputes</div>
      </div>
      <!-- DATATABLE DEMO 1-->
      <div class="card" >
         <div class="card-header">
            <div class="row mx-3">
               <p class="text-primary m-0 font-weight-bold">Open Disputes</p>
               <div class="row ml-auto">
                  <form class="form form-inline mr-2" method="get" action="" id="date-filter">
                     {% csrf_token %}
                     <div class="input-group mr-sm-2">
                        <div class="input-group-prepend">
                           <div class="input-group-text">From</div>
                        </div>
                        <input type="date" name="fdate" id="fdate" class="form-control" />
                     </div>
                     <div class="input-group ">
                        <div class="input-group-prepend">
                           <div class="input-group-text">To</div>
                        </div>
                        <input type="date" name="tdate" id="tdate" class="form-control" />
                     </div>
                     <a name="filter" id="Filter" onclick="filter();" class="form-control btn btn-primary"
                        style="color: white;">Filter
                     </a>
                  </form>
               </div>

               <form class="form form-inline" method="get" action="" id="search">
                   <!-- <input type="search" name="q" id="q" class="form-control" placeholder="Search" />
                   <input type="submit" name="search" value="Search" class="form-control btn btn-primary"> -->
               </form>
            </div>
         </div>
         <div class="card-body" style="width: auto;">

            <table class="table dataTable w-100 no-footer">
               <thead>
                  <tr role="row">
                     <th rowspan="2" colspan="1">By Agent
                     </th>
                     <th rowspan="2" colspan="1">Dispute Date
                     </th>
                     <th rowspan="2" colspan="1">Type
                     </th>
                     <th rowspan="2" colspan="1">Agent's
                        Comment
                     </th>
                     <th rowspan="2" colspan="1">Disputed Time
                     </th>
                     <th style="text-align: center;" rowspan="2" colspan="1">Status
                     </th>
                     <th style="text-align: center;" rowspan="2" colspan="1">Approve Time <br> (min)
                     </th>
                     <th style="text-align: center;" rowspan="2" colspan="1">Comments
                     </th>
                     <th style="text-align: center;" rowspan="2" colspan="1">Actions
                     </th>
                  </tr>
               </thead>
               <tbody>
                  <!--
                  For Performance Reasons Content will be served to data tables as JSON
               -->
                  {% for item in res %}
                  <tr>
                     <td><a href="{% url 'core:super_agent_payroll' item.pk %}" class="btn-link">{{item.employee|title}}</a></td>
                     <td>{{item.dispute_date}}</td>
                     <td>{% if item.type == 'CP_IT' %}
                        CP IT
                        {% elif item.type == 'COACH_TRAIN' %}
                        Coaching/Training
                        {% else %}
                        Client IT
                        {% endif %}
                     </td>
                     <td>{{item.emp_comment|default:'N/A'}}</td>
                     <td>{{item.dispute_time}}</td>
                     <td>{{item.status}}</td>
                     <form action="" method="post" id="payroll_form{{item.pk}}">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{item.pk}}">
                        <td>
                           <input class="form-control" type="number" min="0" name="approve_time">
                        </td>
                        <td>
                           <textarea class="form-control" name="comment" cols="40" rows="5">{{item.comment|default:''}}</textarea>
                        </td>
                        <td>
                           <div class="row">
                              <div class="col my-2 mx-2">
                                 <button type="submit" form="payroll_form{{item.pk}}" value="YES" class="btn btn-success" name="action">
                                    <i class="far fa-calendar-check fa-2x"></i></button>
                              </div>
                              <div class="col my-2 mx-2">
                                 <button type="submit" value="NO" form="payroll_form{{item.pk}}" class="btn btn-danger" name="action">
                                    <i class="fas fa-ban fa-2x"></i></button>
                              </div>
                           </div>
                        </td>
                     </form>
                  </tr>

                  {% endfor %}
                  <tr class="odd">
                     <td valign="top" colspan="9" class="dataTables_empty"></td>
                  </tr>
               </tbody>
            </table>

            {% if res.has_other_pages %}
            <ul class="pagination">
               {% if res.has_previous %}
               <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);"
                     id="{{ res.previous_page_number }}">&laquo;</a></li>
               {% else %}
               <li class="paginate_button page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
               {% endif %}
               {% for i in res.paginator.page_range %}
               {% if res.number == i %}
               <li class="paginate_button page-item active"><span class="page-link">{{ i }} <span
                        class="sr-only">(current)</span></span></li>
               {% else %}
               <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);"
                     id="{{ i }}">{{ i }}</a></li>
               {% endif %}
               {% endfor %}
               {% if res.has_next %}
               <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);"
                     id="{{ res.next_page_number }}">&raquo;</a></li>
               {% else %}
               <li class="paginate_button page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
               {% endif %}
            </ul>
            {% endif %}

         </div>
      </div>

   </div>
</section>

{% endblock content %}

{% block customJs %}
<script>
   function filter() {
      let fdate = document.getElementById('fdate').value;
      let tdate = document.getElementById('tdate').value;
      const filterBtn = document.getElementById('Filter');
      filterBtn.href = "?fdate=" + fdate + "&tdate=" + tdate;
      filterBtn.click();
   };

   function pageFilter(id){
        let paginationLinkBtn = document.getElementById(id);
        console.log(id);
        let queryString = window.location.search;
        if (queryString !== ''){
            const urlParams = new URLSearchParams(queryString);
            if (urlParams.has("fdate") && urlParams.has("tdate")){
                if(urlParams.has("page")){
                    urlParams.set("page",id);
                }else{
                    urlParams.set("page",id);
                }
                console.log("button clicked");
                queryString = "?"+urlParams.toString();
                paginationLinkBtn.href = queryString;
                paginationLinkBtn.click();
                return true;
            }else if (urlParams.has("page")){
               urlParams.set("page",id);
               queryString = "?"+urlParams.toString();
                paginationLinkBtn.href = queryString;
                paginationLinkBtn.click();
                return true;
            }
        }else{
            paginationLinkBtn.href = "?page="+id;
            paginationLinkBtn.click();
            return true;
        }
    };
</script>
{% endblock customJs %}

templates/supervisor/supervisor_acw.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
    After Call Work Logs
{% endblock title %}
    

{% block content %}

<!-- Main section -->
<section class="section-container">
    <!-- Page content -->
    <div class="content-wrapper">
        <div>
            After Call Work Logs
            <small>
                For Approvals
            </small>
        </div>
        <!-- DATATABLE DEMO -->
        <div class="card" style="width: max-width;">
            <div class="card-header">
                <div class="card-title">After Call Work Logs</div>
                <div class="text-sm"></div>
            </div>
            <div class="card-body" style="width: max-width;">
                <div class="table bootgrid">
                    <!-- custom table from the previous project -->
                 <table class="table table-bordered table-hover" id="bootgrid-command" style="color: black;">
                    <thead>
                       <tr role="row" style="background-color: rgba(0, 183, 255, 0.15);word-wrap: normal;">
                           <th rowspan="2" colspan="1" style="text-align: center;width: max-content;" >Date
                           </th>
                           <th rowspan="2" colspan="1" style="text-align: center;" >Agent's Name
                           </th>
                           <th style="text-align: center;"
                               rowspan="2" colspan="1"
                               >ACW (Hrs)
                           </th>
                           <th style="text-align: center;"
                               rowspan="1" colspan="2"
                               >Actions
                           </th>
                       </tr>
                       <tr style="background-color: rgba(0, 183, 255, 0.15);">
                           <th>Approve</th>
                           <th>Decline</th>
                       </tr>
                       </thead>
                       <tbody>
                       <!--
                           For Performance Reasons Content will be served to data tables as JSON
                       -->
                       {% for item in res %}
                           
                                
                       <tr>
                           <td style="width: max-content;">{{item.startdate}}</td>
                           <td>{{item.login_id|title}}</td>
                           <td>{{item.acw_time}}</td>  
                           <td>
                               <form action="
                               {% if request.user.role == 'TEAM_SUP' %}
                                    {% url 'core:super-acw' %}
                                {% else %}
                                    {% url 'core:om-acw' %}
                               {% endif %}
                               " method="post">
                                   {% csrf_token %}
                                   <input type="hidden" name="action" value="YES">
                                   <input type="hidden" name="acw_id" value="{{item.pk}}">
                                   <button type="submit" class="btn btn-success btn-sm" value="Approve" ><i class="far fa-calendar-check fa-2x"></i></button>
                               </form>
                           </td>
     
     
                           <td>
                            <form action="
                            {% if request.user.role == 'TEAM_SUP' %}
                                {% url 'core:super-acw' %}
                            {% else %}
                                {% url 'core:om-acw' %}
                            {% endif %}" 
                            method="post">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="NO">
                                <input type="hidden" name="acw_id" value="{{item.pk}}">
                                <button type="submit" class="btn btn-danger btn-sm" value="Decline" ><i class="fas fa-fist-raised fa-2x"></i></button>
                            </form>
                           </td>     
                       </tr>
     
                       {% endfor %}
                       <tr class="odd">
                           <td valign="top" colspan="9" class="dataTables_empty"></td>
                       </tr>
                       </tbody>
                 </table>
     
                 {% if res.has_other_pages %}
                    <ul class="pagination">
                        {% if res.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">begin</span>
                          </a>
                        </li>   {% endif %}
                        
                        {% for n in res.paginator.page_range %}
                          {% if res.number == n %}
                            <li class="page-item active">
                              <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                            </li>
                          {% elif n > res.number|add:'-3' and n < res.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                          {% endif %}
                        {% endfor %}
                        
                        {% if res.has_next %}
                          <li class="page-item">
                            <a class="page-link" href="?page={{ res.paginator.num_pages }}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">end</span>
                            </a>
                          </li>
                          {% endif %}
                    </ul>
                 {% endif %}
                 
                 </div>
                 
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    