RevenuePayroll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.models import DowntimeTracker
from core.agent_view.agent_view import (AgentHomeView, ApproveDispute,RaiseDispute,PayrollView)
from core.finance_view.finnace_view import FinanceDashboardView, FinanceDisputeView, FinanaceAddressedDisputeView
from core.login_view.login_view import ChangePasswordView, LoginView, LogoutView
from core.supervisor_view.supervisor_view import (DowntimeProcessView, PayrollApprovedView, PayrollNotApprovedView, SupervisorDisputeView,DowntimeTrackerView,SupervisorView,AddAgentView,SupAcwView)

from core.om_view.om_view import OperationsDisputeView, OperationsManagerView,PasswordResetView,OmAddAgentView,DowntimeApprovalView, ProcessAutoDowntimeView,change_supervisor_lob,gen_report, UnattenedDisputeView, UnattenedPayrollView, OmAcwView
from core.utils.common import agent_payroll_view, ajax_get_client, save_email, sup_om_gen_report,approved_disputes
from core.views import maintenance

app_name = 'core'

urlpatterns = [

    # login urls
    path('',LoginView.as_view(),name='login'),
    # url(r'^',maintenance,name='login'),
    path('logout/',LogoutView,name='logout'),
    path('password/change/',ChangePasswordView.as_view(),name='change-password'),
    
    # agents urls
    path('agent/',login_required(AgentHomeView.as_view()),name='home'),
    path('agent/payroll/',PayrollView.as_view(),name='agent-payroll'),
    # dispute related agent urls
    path('agent/approve/',ApproveDispute,name='approve'),
    path('agent/dispute/',RaiseDispute,name='raise-dispute'),


    # operations manager urls
    path('operations/',login_required(OperationsManagerView.as_view()),name='operations'),
    path('operations/reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('operations/add/',OmAddAgentView.as_view(),name='add_agent'),
    path('operations/change_supervisor_lob/',login_required(change_supervisor_lob),name='change_supervisor_lob'),
    path('operations/downtime-approve/',DowntimeApprovalView.as_view(),name='downtime-approve'),
    path('operations/disputes/',OperationsDisputeView.as_view(),name='om-disputes'),
    path('operations/payroll/<pk>/',agent_payroll_view,name='agent_payroll'),
    path('operations/process/downtime/',ProcessAutoDowntimeView.as_view(),name='ops-process-downtime'),
    path('operations/unattended/disputes/',UnattenedDisputeView.as_view(),name='om-unattended-disputes'),
    path('operations/unattended/payrolls/',UnattenedPayrollView.as_view(),name='om-unattended-payrolls'),
    path('operations/acw/',OmAcwView.as_view(),name='om-acw'),
    # path('operations/approved/disputes/',approved_disputes,name='om-approved-disputes'),
    
    # supervisor urls
    path('supervisor/',login_required(SupervisorView.as_view()),name='super-home'),
    path('supervisor/add/',AddAgentView.as_view(),name='super_add_agent'),
    path('profile/',login_required(SupervisorView.as_view()),name='profile'),
    path('supervisor/downtime-tracker/',DowntimeTrackerView.as_view(),name='downtime-tracker'),
    path('supervisor/disputes/',SupervisorDisputeView.as_view(),name='super-disputes'),
    path('supervisor/payroll/<int:pk>/',agent_payroll_view,name='super_agent_payroll'),
    path('supervisor/process/downtime/',DowntimeProcessView.as_view(),name='process-downtime'),
    path('supervisor/payroll/approved/',PayrollApprovedView.as_view(),name='sup-approved-payroll'),
    path('supervisor/payroll/not/approved/',PayrollNotApprovedView.as_view(),name='sup-not-approved-payroll'),
    path('supervisor/acw/',SupAcwView.as_view(),name='super-acw'),
    # path('supervisor/approved/disputes/',approved_disputes,name='sup-approved-disputes'),

    # finacne urls
    path('finance/',FinanceDashboardView.as_view(),name='finance-index'),
    path('finance/disputes/',FinanceDisputeView.as_view(),name='finn-disputes'),
    path('finance/payroll/<pk>/',agent_payroll_view,name='finn_agent_payroll'),
    path('finance/addressed/disputes/',FinanaceAddressedDisputeView.as_view(),name='finn-addressed-dispute'),
    # path('finance/approved/disputes/',approved_disputes,name='finance-approved-disputes'),
    # report export path
    path('export/',gen_report,name='export'),
    path('export-csv/',sup_om_gen_report,name='export-csv'),

    path('save/email/',save_email,name='save-email'),
    path('get/ajax/client', ajax_get_client, name='get_ajax_client'),
]

core/models/Dispute.py
from django.db import models

from core.models import Employee


class Dispute(models.Model):
    type = models.CharField(max_length=255,default='None')
    status = models.CharField(max_length=25,null=False,default='HOLD')
    comment = models.TextField(null=True)
    emp_comment = models.TextField(null=True)
    dispute_time = models.PositiveIntegerField(null=True)
    approve_time = models.PositiveIntegerField(null=True)
    supervisor = models.CharField(max_length=255,null=True)
    employee = models.CharField(max_length=255,null=True)
    dispute_date = models.CharField(max_length=255,null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=False, null=True)
    payroll = models.ForeignKey('Payroll',on_delete=models.SET_NULL,null=True)
    approved_by_sup = models.BooleanField(null=True)
    approved_by_oper_man = models.BooleanField(null=True)
    approved_by_finan = models.BooleanField(null=True)

    sup_approve_date = models.DateField(auto_now_add=False,null=True)
    oper_man_approve_date = models.DateField(auto_now_add=False, null=True)
    finan_approve_date = models.DateField(auto_now_add=False, null=True)

class Roster(models.Model):
    startdate = models.CharField(max_length=255,null=True) # this field is no longer in use
    yearMonth = models.CharField(max_length=255,null=True) # hiredate of an emp
    deluxcode = models.CharField(max_length=255,null=False) # unique employee no. or id
    zipwire = models.CharField(max_length=255,null=False) # same as loginId field in Employee model
    lob = models.CharField(max_length=255,null=False) # group in which an emp may reside
    supervisor = models.CharField(max_length=255,null=False) # sueprvisor name of emp
    client = models.CharField(max_length=255,null=True) # Project Initials for each client

    def __str__(self):
        return f'{self.zipwire} {self.supervisor}'

    @property
    def getName(self):
        return self.zipwire.replace('.',' ').title()

    @property
    def getSupervisorName(self):
        return self.supervisor.replace('.', ' ').title()

class Payroll(models.Model):
    startdate = models.CharField(max_length=255,null=False)
    login_id = models.CharField(max_length=255,null=False)
    login_time = models.CharField(max_length=255,default=0)
    logout_time = models.CharField(max_length=255,default=0)
    total_login_time = models.FloatField(default=0)
    working_time = models.FloatField(default=0)
    lunch_time = models.FloatField( default=0)
    break_time = models.FloatField( default=0)
    not_ready_time = models.FloatField( default=0)
    coaching_time = models.FloatField( default=0)
    training_time = models.FloatField( default=0)
    payroll = models.FloatField(default=0)
    status = models.CharField(max_length=255,default='NEW')
    is_downtime_approved = models.BooleanField(null=True) # this is to check whether the downtime is approved by supervisor or not
    is_om_approve_downtime = models.BooleanField(null=True) # this is to check whether the downtime is approved by om or not
    is_approved = models.BooleanField(default=False)
    client = models.CharField(max_length=255,null=True)
    acw = models.FloatField(default=0)
    is_acw_approved_by_sup = models.BooleanField(null=True) # for AWR accounts only
    is_acw_approved_by_om = models.BooleanField(null=True) # for AWR accounts only

    def __str__(self):
        return f'''{self.login_id} payroll date: {self.startdate}'''

    @property
    def convertLoginId(self):
        return self.login_id.replace('.',' ').title()

    @property
    def getLoginTimeInHours(self):
        return f'{int(self.login_time)}:{int(((self.login_time)*60)%60)}'

    @property
    def getLogoutTimeInHours(self):
        return f'{int(self.logout_time)}:{int(((self.logout_time)*60)%60)}'

    @property
    def getTotalLoginTimeInHours(self):
        h,m = divmod(float(self.total_login_time), 60)
        m = str(m).split('.')[0]
        h = str(h).split('.')[0]
        if len(m) == 1:
            m = '0'+m
        return  f"{h}:{m}"

    @property
    def getWorkingTimeInHours(self):
        h,m = divmod(self.working_time, 60)
        m = str(m).split('.')[0]
        h = str(h).split('.')[0]
        if len(m) == 1:
            m = '0'+m
        return f"{h}:{m}"

    @property
    def getLunchBreakNotReadyTimeInHours(self):
        h,m = divmod((self.lunch_time + self.break_time + self.not_ready_time),60)
        m = str(m).split('.')[0]
        h = str(h).split('.')[0]
        if len(m) == 1:
            m = '0'+m
        return f"{h}:{m}"

    @property
    def getCoachingTrainingTimeInHours(self):
        h,m = divmod((self.coaching_time+ self.training_time), 60)
        m = str(m).split('.')[0]
        h = str(h).split('.')[0]
        if len(m) == 1:
            m = '0'+m
        return f"{h}:{m}"

    @property
    def getPayrollTimeInHours(self):
        h, m = divmod((self.payroll), 60)
        m = str(m).split('.')[0]
        h = str(h).split('.')[0]
        if len(m) == 1:
            m = '0'+m
        return f"{h}:{m}"

core/models/DowntimeTracker.py
from django.db import models

from core.models import Employee


class DowntimeTracker(models.Model):
    created_at = models.DateField(auto_now_add=False,null=True) # contains date when this event is being done
    agent_name = models.CharField(max_length=255,null=True) # contains emp loginId same as of Employee Model
    time_min = models.BigIntegerField(default=0) # time entered in minutes from supervisors end
    remarks = models.TextField(null=True) # reason sent by the supevisor for the addition of downtime
    aux_code = models.CharField(max_length=255,null=True) # events for which agents were occupied in other activities
    approved_by = models.CharField(max_length=255,null=True) # contains operations manager loginId(same as Employee Model)
    zipwire = models.CharField(max_length=255,null=True) # contains supervisor loginId(Same as Employee Model)

    def __str__(self):
        return f'{self.agent_name} has {self.time_min} worked'

    @property
    def getAgentName(self):
        return self.agent_name.replace('.',' ').title()

    @property
    def getRaiserName(self):
        return self.zipwire.replace('.',' ').title()

core/views.py
from django.shortcuts import render, redirect

def maintenance(req):
    return render(req,'maintenance.html')

core/templates/core/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from themicon.co/theme/angle/v4.5/static-html/app/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 13:13:31 GMT -->
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Bootstrap Admin App">
   <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
   <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.jpg' %}">
   <title>Contact Point 360 Solutions</title><!-- =============== VENDOR STYLES ===============-->
   <!-- FONT AWESOME-->
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/brands.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/regular.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/solid.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/fontawesome.css' %}"><!-- SIMPLE LINE ICONS-->
   <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}"><!-- =============== BOOTSTRAP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" id="bscss"><!-- =============== APP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/app.css' %}" id="maincss">
</head>

<body>
   <div class="wrapper">
      <div class="block-center mt-4 wd-xl">
         <!-- START card-->
         <div class="card card-flat">
            <div class="card-header text-center bg-white"><a href="#"><img class="block-center rounded" src="{% static 'images/favicon.jpg' %}" width="20%" alt="Image"></a></div>
            <div class="card-body">
               <p class="text-center py-2">SIGN IN TO CONTINUE.</p>
			   
			   {% if messages %}
				   {% include 'messages.html' %}
			   {% endif %}
				   
               <form class="mb-3" id="loginForm" method="POST" action="{% url 'core:login' %}" novalidate>
				   {% csrf_token %}
                  <div class="form-group">
                     <div class="input-group with-focus">
						 <input class="form-control border-right-0" name="username" id="exampleInputEmail1" type="text" placeholder="Enter Network id" autocomplete="off" required>
                        <div class="input-group-append"><span class="input-group-text text-muted bg-transparent border-left-0"><em class="fa fa-envelope"></em></span></div>
                     </div>
                  </div>
				  <div class="form-group">
					<div class="input-group with-focus">
						<select name="role" id="role" class="form-control border-right-0" aria-required="true" required>
							<option value="None" selected>Select Role...</option>
							<option value="AGT">Agent</option>
							<option value="OPER_MAN">Operations Manager</option>
							<option value="TEAM_SUP">Team lead/Supervisor</option>
							<option value="FIN">Finance</option>
						</select>
					   <div class="input-group-append">
						   <span class="input-group-text text-muted bg-transparent border-left-0">
							   <i class="fas fa-user-tag"></i>
							</span>
						</div>
					</div>
				 </div>
             <div class="form-group">
					<div class="input-group with-focus">
						<select name="client" id="client" class="form-control border-right-0" aria-required="true" required>
							<option value="None" selected>Select Project...</option>
                     {% for client in clients %}
                        <option value="{{client}}">{{client}}</option>
                     {% endfor %}
						</select>
					   <div class="input-group-append">
						   <span class="input-group-text text-muted bg-transparent border-left-0">
							   <i class="fas fa-id-badge"></i>
							</span>
						</div>
					</div>
				 </div>
                  <div class="form-group">
                     <div class="input-group with-focus">
						 <input class="form-control border-right-0" id="exampleInputPassword1" type="password" placeholder="Password" name="password" required>
                        <div class="input-group-append"><span class="input-group-text text-muted bg-transparent border-left-0"><em class="fa fa-lock"></em></span></div>
                     </div>
                  </div>
                  <div class="clearfix">
					<div class="text-center>
						<a class="text-muted" href="#">Forgot your password?</a>
					</div>
                  </div>
				  	<button class="btn btn-block btn-primary mt-3" type="submit">
					  Login
					</button>
               </form>
               <p class="pt-3 text-center">Need to Signup?</p><a class="btn btn-block btn-secondary" href="#register.html">Register Now</a>
            </div>
         </div><!-- END card-->
         <div class="p-3 text-center"><span class="mr-2">&copy;</span><span><script>document.write(new Date().getFullYear());</script></span><span class="mr-2">-</span><span>ContactPoint360</span><br><span>Solutions By Contact Point 360</span></div>
      </div>
   </div><!-- =============== VENDOR SCRIPTS ===============-->
   <!-- MODERNIZR-->
   <script src="{% static 'vendor/modernizr/modernizr.custom.js' %}"></script><!-- STORAGE API-->
   <script src="{% static 'vendor/js-storage/js.storage.js' %}"></script><!-- i18next-->
   <script src="{% static 'vendor/i18next/i18next.js' %}"></script>
   <script src="{% static 'vendor/i18next-xhr-backend/i18nextXHRBackend.js' %}"></script><!-- JQUERY-->
   <script src="{% static 'vendor/jquery/dist/jquery.js' %}"></script><!-- BOOTSTRAP-->
   <script src="{% static 'vendor/popper.js/dist/umd/popper.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.js' %}"></script><!-- PARSLEY-->
   <script src="{% static 'vendor/parsleyjs/dist/parsley.js' %}"></script><!-- =============== APP SCRIPTS ===============-->
   <script src="{% static 'js/app.js' %}"></script>
</body>

</html>