RevenuePayroll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.models import DowntimeTracker
from core.agent_view.agent_view import (AgentHomeView, ApproveDispute,RaiseDispute,PayrollView)
from core.finance_view.finnace_view import FinanceDashboardView, FinanceDisputeView, FinanaceAddressedDisputeView
from core.login_view.login_view import ChangePasswordView, LoginView, LogoutView
from core.supervisor_view.supervisor_view import (DowntimeProcessView, PayrollApprovedView, PayrollNotApprovedView, SupervisorDisputeView,DowntimeTrackerView,SupervisorView,AddAgentView,SupAcwView)

from core.om_view.om_view import OperationsDisputeView, OperationsManagerView,PasswordResetView,OmAddAgentView,DowntimeApprovalView, ProcessAutoDowntimeView,change_supervisor_lob,gen_report, UnattenedDisputeView, UnattenedPayrollView, OmAcwView
from core.utils.common import agent_payroll_view, ajax_get_client, save_email, sup_om_gen_report,approved_disputes
from core.views import maintenance

app_name = 'core'

urlpatterns = [

    # login urls
    path('',LoginView.as_view(),name='login'),
    # url(r'^',maintenance,name='login'),
    path('logout/',LogoutView,name='logout'),
    path('password/change/',ChangePasswordView.as_view(),name='change-password'),
    
    # agents urls
    path('agent/',login_required(AgentHomeView.as_view()),name='home'),
    path('agent/payroll/',PayrollView.as_view(),name='agent-payroll'),
    # dispute related agent urls
    path('agent/approve/',ApproveDispute,name='approve'),
    path('agent/dispute/',RaiseDispute,name='raise-dispute'),


    # operations manager urls
    path('operations/',login_required(OperationsManagerView.as_view()),name='operations'),
    path('operations/reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('operations/add/',OmAddAgentView.as_view(),name='add_agent'),
    path('operations/change_supervisor_lob/',login_required(change_supervisor_lob),name='change_supervisor_lob'),
    path('operations/downtime-approve/',DowntimeApprovalView.as_view(),name='downtime-approve'),
    path('operations/disputes/',OperationsDisputeView.as_view(),name='om-disputes'),
    path('operations/payroll/<pk>/',agent_payroll_view,name='agent_payroll'),
    path('operations/process/downtime/',ProcessAutoDowntimeView.as_view(),name='ops-process-downtime'),
    path('operations/unattended/disputes/',UnattenedDisputeView.as_view(),name='om-unattended-disputes'),
    path('operations/unattended/payrolls/',UnattenedPayrollView.as_view(),name='om-unattended-payrolls'),
    path('operations/acw/',OmAcwView.as_view(),name='om-acw'),
    # path('operations/approved/disputes/',approved_disputes,name='om-approved-disputes'),
    
    # supervisor urls
    path('supervisor/',login_required(SupervisorView.as_view()),name='super-home'),
    path('supervisor/add/',AddAgentView.as_view(),name='super_add_agent'),
    path('profile/',login_required(SupervisorView.as_view()),name='profile'),
    path('supervisor/downtime-tracker/',DowntimeTrackerView.as_view(),name='downtime-tracker'),
    path('supervisor/disputes/',SupervisorDisputeView.as_view(),name='super-disputes'),
    path('supervisor/payroll/<int:pk>/',agent_payroll_view,name='super_agent_payroll'),
    path('supervisor/process/downtime/',DowntimeProcessView.as_view(),name='process-downtime'),
    path('supervisor/payroll/approved/',PayrollApprovedView.as_view(),name='sup-approved-payroll'),
    path('supervisor/payroll/not/approved/',PayrollNotApprovedView.as_view(),name='sup-not-approved-payroll'),
    path('supervisor/acw/',SupAcwView.as_view(),name='super-acw'),
    # path('supervisor/approved/disputes/',approved_disputes,name='sup-approved-disputes'),

    # finacne urls
    path('finance/',FinanceDashboardView.as_view(),name='finance-index'),
    path('finance/disputes/',FinanceDisputeView.as_view(),name='finn-disputes'),
    path('finance/payroll/<pk>/',agent_payroll_view,name='finn_agent_payroll'),
    path('finance/addressed/disputes/',FinanaceAddressedDisputeView.as_view(),name='finn-addressed-dispute'),
    # path('finance/approved/disputes/',approved_disputes,name='finance-approved-disputes'),
    # report export path
    path('export/',gen_report,name='export'),
    path('export-csv/',sup_om_gen_report,name='export-csv'),

    path('save/email/',save_email,name='save-email'),
    path('get/ajax/client', ajax_get_client, name='get_ajax_client'),
]

templates/approved_dispute_logs.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
{{request.user}} | Approved Disputes Logs
{% endblock title %}


{% block content %}

<!-- Main section -->
<section class="section-container">
    <!-- Page content -->
    <div class="content-wrapper">
        <!-- DATATABLE DEMO -->
        <div class="row">     
            <div class="card-group" >
                {% for item in res %}
                <div class="col-3">
                    <div class="card text-center border-success mb-3 mr-3" >
                        <div class="card-body text-success">
                            <!-- here put the code for card layout to show the agents that have approved disputes -->
                            <p class="card-text">
                                {{item.employee}}
                            </p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">
                                {% if request.user.role == 'TEAM_SUP' %}
                                    Disputed On: {{item.dispute_date}} | Approved On: {{item.sup_approve_date}}
                                {% elif request.user.role == 'OPER_MAN' %}
                                Disputed On: {{item.dispute_date}} | Approved On: {{item.oper_man_approve_date}}
                                {% elif request.user.role == 'FIN' %}
                                Disputed On: {{item.dispute_date}} | Approved On: {{item.finan_approve_date}}
                                {% endif %}
                            </small>
                        </div>
                    </div>
                </div>
                {% endfor %}

                {% if res.has_other_pages %}
                <ul class="pagination">
                    {% if res.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">begin</span>
                        </a>
                    </li> {% endif %}

                    {% for n in res.paginator.page_range %}
                    {% if res.number == n %}
                    <li class="page-item active">
                        <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                    </li>
                    {% elif n > res.number|add:'-3' and n < res.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if res.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ res.paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">end</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <meta name="description"
          content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon  -->
    <link rel="icon" type="image/png"
          src="{% static 'images/favicon.jpg' %}" sizes="32x32">

    <!-- ALL CSS PACKAGES HERE -->

    <!--Bootstrap 4-->
    <link rel="stylesheet" href="{% static 'scorebuddy/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'scorebuddy/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'scorebuddy/css.css' %}">
    <link rel="stylesheet" href="{% static 'scorebuddy/chosen.css' %}">

    <!-- Parsley Validator -->
    <link href="{% static 'scorebuddy/parsley.css' %}" rel="stylesheet" type="text/css">

    <!-- Ajax Upload -->
    <link href="{% static 'scorebuddy/fine-uploader-gallery.css' %}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'scorebuddy/bootstrap4-toggle.min.css' %}">

    <!-- Bootstrap Select -->
    <link rel="stylesheet" href="{% static 'scorebuddy/bootstrap-select.css' %}">

    <!--Custom Date Range Picker-->
    <link rel="stylesheet" type="text/css" href="{% static 'scorebuddy/daterangepicker.css' %}">

    <!-- fancyBox -->
    <link rel="stylesheet" type="text/css" href="{% static 'scorebuddy/jquery.css' %}s">


    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="{% static 'scorebuddy/font-awesome.css' %}" type="text/css">


    <link rel="stylesheet" href="{% static 'scorebuddy/bootstrap-datepicker.css' %}">


    <link rel="stylesheet" href="{% static 'scorebuddy/dataTables.css' %}">
    <link rel="stylesheet" href="{% static 'scorebuddy/fixedColumns.css' %}">


    <!-- Quill Textbox -->
    <link href="{% static 'scorebuddy/quill.css' %}" rel="stylesheet">


    <!-- Alertify JS -->
    <link rel="stylesheet" href="{% static 'scorebuddy/alertify.css' %}" type="text/css">

    <link rel="stylesheet" href="{% static 'scorebuddy/icofont.css' %}">

    <!-- CUSTOM CSS HERE  -->
    <link rel="stylesheet" href="{% static 'scorebuddy/main.css' %}">


    <link rel="stylesheet" type="text/css" href="{% static 'scorebuddy/reports.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'scorebuddy/reports-filter.css' %}">


    <!-- ALL JS PACKAGES HERE -->
<!--    <script src="{% static 'scorebuddy/jquery.min.js' %}"></script>-->
<!--    <style>@media print {#ghostery-tracker-tally {display:none !important}}</style>-->
<!--    <script src="{% static 'scorebuddy/popper.min.js' %}"></script>-->

    <!--Bootstrap 4-->
<!--    <script src="{% static 'scorebuddy/bootstrap.js' %}"></script>-->

    <!-- Bootstrap Select -->
    <script src="{% static 'scorebuddy/bootstrap-select.min.js' %}"></script>

    <script src="{% static 'scorebuddy/jquery-ui.min.js' %}"></script>

    <!-- Custom Date Range Picker & Moment JS -->
    <script src="{% static 'scorebuddy/moment.min.js' %}"></script>
    <script src="{% static 'scorebuddy/daterangepicker.js' %}"></script>

    <script src="{% static 'scorebuddy/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'scorebuddy/highcharts.js' %}"></script>
    <script src="{% static 'scorebuddy/quill.min.js' %}"></script>
<!--    <script src="{% static 'scorebuddy/bootstrap4-toggle.min.js' %}"></script>-->






    <!-- JQuery Time Selector Add-On -->
    <script src="{% static 'scorebuddy/jquery-ui-timepicker-addon.js' %}"></script>


    <!-- Audio Pop Up -->
    <script src="{% static 'scorebuddy/BatmoAudioPop.js' %}"></script>

    <script src="{% static 'scorebuddy/main.js' %}"></script>
    <style type="text/css">a[data-v-82963a40]{cursor:pointer}</style>
    <style type="text/css">a[data-v-82963a40]{cursor:pointer}</style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">

</head>
<body data-new-gr-c-s-check-loaded="8.881.0" data-gr-ext-installed="">
<div id="wrapper" class="wrapper">
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}

  {% endblock content %}
    <div class="push"></div>
</div>
<footer class="footer">
    <div class="container-fluid max-width">
        <div class="footer-nav  no-padding">
            <div class="d-flex justify-content-between bd-highlight mb-3">
                <div class="p-0 ">
                    <a href="#" target="_blank">

                    </a>
                </div>
                <div class="p-0 ">
                    <ul class="nav ">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Help
                                &amp; Support</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link grey" href="#" target="_blank">
                                Powered by ContactPoint360 © 2021
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

{% block customJs %}

{% endblock customJs %}

<script src="{% static 'scorebuddy/footer.js' %}"></script>
<script src="{% static 'scorebuddy/my-courses.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ request.user.loginId }} | {{title}}
{% endblock title %}

{% block content %}
<main class=" container-fluid px-2">

    <div class="card shadow-lg o-hidden border-0 my-5">
        <div class="card-body p-0">
            <div class="row justify-content-center">

                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h4 class="text-dark mb-4">Change Password!</h4>
                        </div>
                        <form action="" method="post" class="user">
                            {% csrf_token %}
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input class="form-control form-control-user" type="password" id="currentPassword"
                                           aria-describedby="currentPasswordHelp" placeholder="Current Password"
                                           name="currentPassword" required>
                                </div>
                                <div class="col-sm-6">
                                    <input class="form-control form-control-user" type="password" id="new_password1"
                                           aria-describedby="new_password1Help" placeholder="New Password"
                                           name="new_password1" minlength="6" required>
                                </div>
                            </div>
                            <div class="form-group">
                                    <input class="form-control form-control-user" type="password" id="new_password2"
                                           aria-describedby="new_password2Help" placeholder="Confirm Password"
                                           name="new_password2" minlength="6" required>
                            </div>
                            <button class="btn btn-primary btn-block text-white btn-user"
                                    type="submit">Confirm
                            </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div id="below-main-container"></div>
</main>
{% endblock content %}

templates/declined_dispute_logs.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
    {{requst.user.loginId}} | Declined Disputes Logs
{% endblock title %}
    

{% block content %}

<!-- Main section -->
<section class="section-container">
    <!-- Page content -->
    <div class="content-wrapper">
        <!-- DATATABLE DEMO -->
        <div class="card"  style="width: max-width;">
            <div class="card-header">
                <div class="card-title">Declined disputes Logs</div>
                <div class="text-sm"></div>
            </div>
            <div class="card-group" style="width: max-content;">
                {% for item in res %}
                <div class="card border-danger mb-3" style="max-width: 18rem;">
                    <div class="card-body text-danger" style="width: max-width;">
                        <!-- here put the code for card layout to show the agents that have approved disputes -->
                        <p class="card-text">
                            {{item.employee}}
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            {% if request.user.role == 'TEAM_SUP' %}
                                {{item.sup_approve_date}}
                            {% elif request.user.role == 'OPER_MAN' %}
                                {{item.oper_man_approve_date}}
                            {% elif request.user.role == 'FIN' %}
                                {{item.finan_approve_date}}
                            {% endif %}
                        </small>
                    </div>
                </div>
                {% endfor %}

                {% if res.has_other_pages %}
                <ul class="pagination">
                    {% if res.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">begin</span>
                        </a>
                    </li> {% endif %}

                    {% for n in res.paginator.page_range %}
                    {% if res.number == n %}
                    <li class="page-item active">
                        <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                    </li>
                    {% elif n > res.number|add:'-3' and n < res.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if res.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ res.paginator.num_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">end</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/email_check.html
<!-- Modal -->
<div class="modal fade" id="emailCheck" tabindex="-1" aria-labelledby="emailCheckLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
         <div class="modal-header" style="background-color: #402543;">
            <h5 class="modal-title" id="emailCheckLabel" style="color: white;">Provide Your Email!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <div class="row mx-2 my-2 justify-content-center">
               <form class="form form-inline mx-2" method="get" action="{% url 'core:save-email' %}"
                  id="saveEmail">
                  {% csrf_token %}
                  <div class="row">
                     <div class="col-12">
                        <div class="input-group">
                           <div class="input-group-prepend">
                              <div class="input-group-text">Work Email</div>
                           </div>
                           <input class="form-control" id="work_mail" name="work_mail" type="email"
                              placeholder="Enter your work email!" />
                        </div>
                     </div>
                  </div>
               </form>
            </div>
         </div>
         <div class="modal-footer">
            <button type="submit" form="saveEmail" class="btn btn-primary">Save</button>
         </div>
      </div>
   </div>
</div>

templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="https://contactpoint360.com/">
                        Home
                    </a>
                </li>

            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">ContactPoint360</a>, Agent Schedule System &reg;.
        </p>
    </div>
</footer>

templates/messages.html
{% if messages %}

        {% for message in messages %}
    <div 
        {% if message.tags %}
            class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show"
        {% endif %} 
    role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

{% endif %}

templates/new_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from themicon.co/theme/angle/v4.5/static-html/app/dashboard_h.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 13:12:03 GMT -->
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Bootstrap Admin App">
   <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
   <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.jpg' %}">
   <title>
       
       {% block title %}
           
       {% endblock title %}
           
   </title><!-- =============== VENDOR STYLES ===============-->
   <!-- FONT AWESOME-->
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/brands.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/regular.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/solid.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/fontawesome.css' %}"><!-- SIMPLE LINE ICONS-->
   <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}"><!-- ANIMATE.CSS-->
   <link rel="stylesheet" href="{% static 'vendor/animate.css/animate.css' %}"><!-- WHIRL (spinners)-->
   <link rel="stylesheet" href="{% static 'vendor/whirl/dist/whirl.css' %}"><!-- =============== PAGE VENDOR STYLES ===============-->
   <!-- WEATHER ICONS-->
   <link rel="stylesheet" href="{% static 'vendor/weather-icons/css/weather-icons.css' %}"><!-- =============== BOOTSTRAP STYLES ===============-->
   
   <link rel="stylesheet" href="{% static 'vendor/jquery-bootgrid/dist/jquery.bootgrid.css' %}" id="bscss"><!-- =============== APP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" id="bscss"><!-- =============== APP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/app.css' %}" id="maincss">
</head>

<body class="">
   <div class="wrapper">
      {% include 'navbar.html' %}
      {% block content %}
         
      
      {% endblock content %}
   </div>

<!-- =============== VENDOR SCRIPTS ===============-->
   <!-- MODERNIZR-->
   <script src="{% static 'vendor/modernizr/modernizr.custom.js' %}"></script><!-- STORAGE API-->
   <script src="{% static 'vendor/js-storage/js.storage.js' %}"></script><!-- SCREENFULL-->
   <script src="{% static 'vendor/screenfull/dist/screenfull.js' %}"></script><!-- i18next-->
   <script src="{% static 'vendor/i18next/i18next.js' %}"></script>
   <script src="{% static 'vendor/i18next-xhr-backend/i18nextXHRBackend.js' %}"></script>
   <script src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
   <script src="{% static 'vendor/popper.js/dist/umd/popper.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.js' %}"></script><!-- =============== PAGE VENDOR SCRIPTS ===============-->
   <!-- SPARKLINE-->
   <script src="{% static 'vendor/jquery-sparkline/jquery.sparkline.js' %}"></script><!-- FLOT CHART-->
   <script src="{% static 'vendor/flot/jquery.flot.js' %}"></script>
   <script src="{% static 'vendor/jquery.flot.tooltip/js/jquery.flot.tooltip.js' %}"></script>
   <script src="{% static 'vendor/flot/jquery.flot.resize.js' %}"></script>
   <script src="{% static 'vendor/flot/jquery.flot.pie.js' %}"></script>
   <script src="{% static 'vendor/flot/jquery.flot.time.js' %}"></script>
   <script src="{% static 'vendor/flot/jquery.flot.categories.js' %}"></script>
   <script src="{% static 'vendor/jquery.flot.spline/jquery.flot.spline.js' %}"></script><!-- EASY PIE CHART-->
   <script src="{% static 'vendor/easy-pie-chart/dist/jquery.easypiechart.js' %}"></script><!-- MOMENT JS-->
   <script src="{% static 'vendor/moment/min/moment-with-locales.js' %}"></script><!-- =============== APP SCRIPTS ===============-->
   <script src="{% static 'js/app.js' %}"></script>
   <script src="{% static 'js/notify.js' %}"></script>
   
   
   {% if messages %}
      
      {% for message in messages %}
         <script>
            $.notify(
               "{{message}}",
            "{{message.tags}}"
        );
         </script>
      {% endfor %}
         
   {% endif %}
      
   
   {% block customJs %}
      
   {% endblock customJs %}

   
   {% if request.user.email is None %}
   <script>
      $(
         function(){
            $('#emailCheck').modal({
           'show': true
        });
         }
      );
   </script>
   {% endif %}

   
   {% if request.user.role == 'FIN' %}
      <script>
         $('#client').focusout(function (e){
            e.preventDefault();
            // get the lob from modal dropdown
            let client = $(this).val();
            // GET AJAX request
            $.ajax({
               type:'GET',
               url: "{% url 'core:get_ajax_client' %}",
               data: {"client":client},
               success: function (resp){
                  // if not a client, alert the user
                  if(!resp["lob"]){
                     alert("Server is busy... Please try again!");
                     let LOB = $('#client');
                     LOB.val("");
                     LOB.focus();
                  }else{
                     $('#lob').empty();
                     resp.lob.forEach((item) => {
                        $('#lob').append(`<option value="${item}">${item}</option>`);
                     });
                  }
               },
               error: function(resp){
                  console.log(resp);
               }
            });
         });
      </script>
   {% endif %}
      
      
      
</body>

</html>