RevenuePayroll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.models import DowntimeTracker
from core.agent_view.agent_view import (AgentHomeView, ApproveDispute,RaiseDispute,PayrollView)
from core.finance_view.finnace_view import FinanceDashboardView, FinanceDisputeView, FinanaceAddressedDisputeView
from core.login_view.login_view import ChangePasswordView, LoginView, LogoutView
from core.supervisor_view.supervisor_view import (DowntimeProcessView, PayrollApprovedView, PayrollNotApprovedView, SupervisorDisputeView,DowntimeTrackerView,SupervisorView,AddAgentView,SupAcwView)

from core.om_view.om_view import OperationsDisputeView, OperationsManagerView,PasswordResetView,OmAddAgentView,DowntimeApprovalView, ProcessAutoDowntimeView,change_supervisor_lob,gen_report, UnattenedDisputeView, UnattenedPayrollView, OmAcwView
from core.utils.common import agent_payroll_view, ajax_get_client, save_email, sup_om_gen_report,approved_disputes
from core.views import maintenance

app_name = 'core'

urlpatterns = [

    # login urls
    path('',LoginView.as_view(),name='login'),
    # url(r'^',maintenance,name='login'),
    path('logout/',LogoutView,name='logout'),
    path('password/change/',ChangePasswordView.as_view(),name='change-password'),
    
    # agents urls
    path('agent/',login_required(AgentHomeView.as_view()),name='home'),
    path('agent/payroll/',PayrollView.as_view(),name='agent-payroll'),
    # dispute related agent urls
    path('agent/approve/',ApproveDispute,name='approve'),
    path('agent/dispute/',RaiseDispute,name='raise-dispute'),


    # operations manager urls
    path('operations/',login_required(OperationsManagerView.as_view()),name='operations'),
    path('operations/reset_password/',PasswordResetView.as_view(),name='reset_password'),
    path('operations/add/',OmAddAgentView.as_view(),name='add_agent'),
    path('operations/change_supervisor_lob/',login_required(change_supervisor_lob),name='change_supervisor_lob'),
    path('operations/downtime-approve/',DowntimeApprovalView.as_view(),name='downtime-approve'),
    path('operations/disputes/',OperationsDisputeView.as_view(),name='om-disputes'),
    path('operations/payroll/<pk>/',agent_payroll_view,name='agent_payroll'),
    path('operations/process/downtime/',ProcessAutoDowntimeView.as_view(),name='ops-process-downtime'),
    path('operations/unattended/disputes/',UnattenedDisputeView.as_view(),name='om-unattended-disputes'),
    path('operations/unattended/payrolls/',UnattenedPayrollView.as_view(),name='om-unattended-payrolls'),
    path('operations/acw/',OmAcwView.as_view(),name='om-acw'),
    # path('operations/approved/disputes/',approved_disputes,name='om-approved-disputes'),
    
    # supervisor urls
    path('supervisor/',login_required(SupervisorView.as_view()),name='super-home'),
    path('supervisor/add/',AddAgentView.as_view(),name='super_add_agent'),
    path('profile/',login_required(SupervisorView.as_view()),name='profile'),
    path('supervisor/downtime-tracker/',DowntimeTrackerView.as_view(),name='downtime-tracker'),
    path('supervisor/disputes/',SupervisorDisputeView.as_view(),name='super-disputes'),
    path('supervisor/payroll/<int:pk>/',agent_payroll_view,name='super_agent_payroll'),
    path('supervisor/process/downtime/',DowntimeProcessView.as_view(),name='process-downtime'),
    path('supervisor/payroll/approved/',PayrollApprovedView.as_view(),name='sup-approved-payroll'),
    path('supervisor/payroll/not/approved/',PayrollNotApprovedView.as_view(),name='sup-not-approved-payroll'),
    path('supervisor/acw/',SupAcwView.as_view(),name='super-acw'),
    # path('supervisor/approved/disputes/',approved_disputes,name='sup-approved-disputes'),

    # finacne urls
    path('finance/',FinanceDashboardView.as_view(),name='finance-index'),
    path('finance/disputes/',FinanceDisputeView.as_view(),name='finn-disputes'),
    path('finance/payroll/<pk>/',agent_payroll_view,name='finn_agent_payroll'),
    path('finance/addressed/disputes/',FinanaceAddressedDisputeView.as_view(),name='finn-addressed-dispute'),
    # path('finance/approved/disputes/',approved_disputes,name='finance-approved-disputes'),
    # report export path
    path('export/',gen_report,name='export'),
    path('export-csv/',sup_om_gen_report,name='export-csv'),

    path('save/email/',save_email,name='save-email'),
    path('get/ajax/client', ajax_get_client, name='get_ajax_client'),
]

templates/om/downtime_approve.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
Downtime Approve
{% endblock title %}

{% block content %}
<style>
    .modal-backdrop {
     /* bug fix - no overlay */    
     display: none;    
 }
 </style>
<section class="section-container">
    <div class="content-wrapper">
        <div class="card w-100">
            <div class="card-header">Downtime Tracker Logs<div class="text-sm">For Approvals</div>
            </div>
            <div class="table-responsive bootgrid">
                <table class="table table-striped bootgrid-table" id="bootgrid-command" aria-busy="false">
                    <thead class="text-center">
                        <tr>
                            <th data-column-id="date" class="text-left"><span class="text">Date</span><span class="icon fa "></span></th>
                            <th data-column-id="raisedBy" class="text-left"><span class="text">Raised By</span><span class="icon fa "></span></th>
                            <th data-column-id="AgentName" class="text-left"><span class="text">Agent Name</span><span class="icon fa "></span></th>
                            <th data-column-id="time" class="text-left"><span class="text">Time <br>(min)</span><span class="icon fa fa-sort-desc"></span></th>
                            <th data-column-id="AuxCode" class="text-left"><span class="text">Aux Code <br>(By Supervisor)</span><span class="icon fa fa-sort-desc"></span></th>
                            <th data-column-id="Remarks" class="text-left"><span class="text">Remarks <br>(By Supervisor)</span><span class="icon fa fa-sort-desc"></span></th>
                            <th data-column-id="Actions" class="text-left"<span class="text">Actions</span><span class="icon fa "></span></th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        
                        {% for it in res %}
                        <tr data-row-id="{{it.pk}}">
                            <td class="text-left">{{it.created_at}}</td>
                            <td class="text-left">{{it.getRaiserName}}</td>
                            <td class="text-left">{{it.getAgentName}}</td>
                            <td class="text-left">{{it.time_min|default:'N/A'}}</td>
                            <td class="text-left">{{it.aux_code|default:'N/A'}}</td>
                            <td class="text-left">{{it.remarks}}</td>
                            <td class="text-left">
                                <form class="form my-1" action="" method="post" id="form{{it.pk}}">
                                    {% csrf_token %}
                                    <input type="hidden" name="tracker_id" value="{{it.pk}}">
                                    <button type="submit" class="btn btn-sm btn-info mr-2 command-edit" 
                                    form="form{{it.pk}}" data-row-id="{{it.pk}}" name="action" value="YES" style="background-color: rgb(44, 199, 44);">
                                        <em class="fa fa-thumbs-up fa-fw"></em>
                                    </button>
                                </form>
                                <button type="button" class="btn btn-sm btn-danger command-delete" data-row-id="{{it.pk}}" data-toggle="modal" data-target="#exampleModal{{it.pk}}" style="background-color: rgb(211, 47, 47);">
                                    <em class="fa fa-trash fa-fw"></em>
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal{{it.pk}}" tabindex="-1"
                                aria-labelledby="exampleModalLabel" aria-hidden="true">
                               <div class="modal-dialog modal-dialog-centered">
                                   <div class="modal-content">
                                       <div class="modal-header text-center">
                                           <h5 class="modal-title" id="exampleModalLabel">Reasons</h5>
                                           <button type="button" class="close" data-dismiss="modal"
                                                   aria-label="Close">
                                               <span aria-hidden="true">&times;</span>
                                           </button>
                                       </div>
                                       <div class="modal-body">
                                           <form action="" method="post" id="reasonForm{{it.pk}}" class="form">
                                               {% csrf_token %}
                                               <input type="hidden" name="tracker_id" value="{{it.pk}}">
                                               <div class="form-group">
                                                   <div class="row row mx-2">
                                                       <textarea cols="10" rows="10" name="reasonArea" class="form-control"  placeholder="Reason for declining the agent's dispute..."></textarea>
                                                   </div>
                                               </div>
                                           </form>
                                       </div>
                                       <div class="modal-footer">
                                           <button type="button" class="btn btn-secondary"
                                                   data-dismiss="modal">Cancel
                                           </button>
                                           <button type="submit" form="reasonForm{{it.pk}}" class="btn btn-danger" name="action" value="NO">
                                               Send & Decline
                                           </button>
                                       </div>
                                   </div>
                               </div>
                           </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/om/om_acw.html
{% extends 'new_base.html' %}
{% load static %}

{% block title %}
    After Call Work Logs
{% endblock title %}
    

{% block content %}

<!-- Main section -->
<section class="section-container">
    <!-- Page content -->
    <div class="content-wrapper">
        <div>
            After Call Work Logs
            <small>
                For Approvals
            </small>
        </div>
        <!-- DATATABLE DEMO -->
        <div class="card" style="width: max-width;">
            <div class="card-header">
                <div class="card-title">After Call Work Logs</div>
                <div class="text-sm"></div>
            </div>
            <div class="card-body" style="width: max-width;">
                <div class="table bootgrid">
                    <!-- custom table from the previous project -->
                 <table class="table table-bordered table-hover" id="bootgrid-command" style="color: black;">
                    <thead>
                       <tr role="row" style="background-color: rgba(0, 183, 255, 0.15);word-wrap: normal;">
                           <th rowspan="2" colspan="1" style="text-align: center;width: max-content;" >Date
                           </th>
                           <th rowspan="2" colspan="1" style="text-align: center;" >Agent's Name
                           </th>
                           <th style="text-align: center;"
                               rowspan="2" colspan="1"
                               >ACW (Hrs)
                           </th>
                           <th style="text-align: center;"
                               rowspan="1" colspan="2"
                               >Actions
                           </th>
                       </tr>
                       <tr style="background-color: rgba(0, 183, 255, 0.15);">
                           <th>Approve</th>
                           <th>Decline</th>
                       </tr>
                       </thead>
                       <tbody>
                       <!--
                           For Performance Reasons Content will be served to data tables as JSON
                       -->
                       {% for item in res %}
                           
                                
                       <tr>
                           <td style="width: max-content;">{{item.startdate}}</td>
                           <td>{{item.login_id|title}}</td>
                           <td>{{item.acw_time}}</td>  
                           <td>
                               <form action="
                               {% if request.user.role == 'TEAM_SUP' %}
                                    {% url 'core:super-acw' %}
                                {% else %}
                                    {% url 'core:om-acw' %}
                               {% endif %}
                               " method="post">
                                   {% csrf_token %}
                                   <input type="hidden" name="action" value="YES">
                                   <input type="hidden" name="acw_id" value="{{item.pk}}">
                                   <button type="submit" class="btn btn-success btn-sm" value="Approve" ><i class="far fa-calendar-check fa-2x"></i></button>
                               </form>
                           </td>
     
     
                           <td>
                            <form action="
                            {% if request.user.role == 'TEAM_SUP' %}
                                {% url 'core:super-acw' %}
                            {% else %}
                                {% url 'core:om-acw' %}
                            {% endif %}" 
                            method="post">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="NO">
                                <input type="hidden" name="acw_id" value="{{item.pk}}">
                                <button type="submit" class="btn btn-danger btn-sm" value="Decline" ><i class="fas fa-fist-raised fa-2x"></i></button>
                            </form>
                           </td>     
                       </tr>
     
                       {% endfor %}
                       <tr class="odd">
                           <td valign="top" colspan="9" class="dataTables_empty"></td>
                       </tr>
                       </tbody>
                 </table>
     
                 {% if res.has_other_pages %}
                    <ul class="pagination">
                        {% if res.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">begin</span>
                          </a>
                        </li>   {% endif %}
                        
                        {% for n in res.paginator.page_range %}
                          {% if res.number == n %}
                            <li class="page-item active">
                              <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                            </li>
                          {% elif n > res.number|add:'-3' and n < res.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                          {% endif %}
                        {% endfor %}
                        
                        {% if res.has_next %}
                          <li class="page-item">
                            <a class="page-link" href="?page={{ res.paginator.num_pages }}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">end</span>
                            </a>
                          </li>
                          {% endif %}
                    </ul>
                 {% endif %}
                 
                 </div>
                 
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/om/om_agent_disputes.html
{% extends 'new_base.html' %}
{% load static %}


{% block title %}
    {{title}}
{% endblock title %}
    


{% block content %}
<style>
    .modal-backdrop {
     /* bug fix - no overlay */    
     display: none;    
 }
 </style>
 <!-- Main section-->
 <section class="section-container">
    <!-- Page content-->
    <div class="content-wrapper">
       <!-- DATATABLE DEMO 1-->
       <div class="card" >
          <div class="card-header">
              <div class="row mx-3">
                <p class="text-primary m-0 font-weight-bold">Open Dispute</p>
                <div class="row ml-auto">
                    <form class="form form-inline mr-2" method="get" action="" id="date-filter">
                        {% csrf_token %}
                        <div class="input-group mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">From</div>
                            </div>
                            <input type="date" name="fdate" id="fdate" class="form-control" />
                        </div>
                        <div class="input-group ">
                            <div class="input-group-prepend">
                                <div class="input-group-text">To</div>
                            </div>
                            <input type="date" name="tdate" id="tdate" class="form-control" />
                        </div>
                        <a name="filter" id="Filter" onclick="filter();" class="form-control btn btn-primary" style="color: white;">Filter
                        </a>
                    </form>
                    <div class="">
                        <a name="exportCSV" data-toggle="modal" data-target="#exportCSVModal" data-placement="top" title="Export dispute csv" class="form-control btn btn-primary" style="color: white;"><i class="fas fa-download"></i>
                        </a>
                    </div>
                </div>

              </div>
             
          </div>
          <div class="card-body" style="width: auto;">
             
            <table class="table dataTable my-0" id="dataTable">
                <thead class="text-center">
                    <tr>
                        <th rowspan="2" colspan="1">Date</th>
                        <th rowspan="2" colspan="1">Raised By</th>
                        <th rowspan="2" colspan="1">Disputed Time <br> (min)</th>
                        <th rowspan="2" colspan="1">Approved Time <br> (By Supervisor)</th>
                        <th rowspan="2" colspan="1">Dispute Status</th>
                        <th rowspan="2" colspan="1">Agent's Comment</th>
                        <th rowspan="2" colspan="1">Supervisor Comments</th>
                        <th rowspan="1" colspan="2">Actions</th>
                    </tr>
                <tr>
                    <th>Approve</th>
                    <th>Decline</th>
                </tr>
                </thead>
                <tbody class="text-center">
                {% for it in res %}
                    <tr>
                        <td>{{it.dispute_date}}</td>
                        <td><a href="{% url 'core:agent_payroll' it.pk %}" class="btn-link"
                        >{{it.employee }}</a></td>
                        <td>{{it.dispute_time|default:'N/A'}}</td>
                        <td>{{it.approve_time|default:'N/A'}}</td>
                        <td>{{it.status}}</td>
                        <td>{{it.emp_comment}}</td>
                        <td>{{it.comment}}</td>
                        <!-- <form action="" method="post" id="form{{ it.pk }}"> -->
                            <input type="hidden" name="dispute_id" value="{{it.pk}}">
                            <td>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#approveTimeModal{{it.pk}}">
                                    <i class="far fa-calendar-check fa-2x"></i>
                                </button>
                            </td>

                            <!-- Modal -->
                            <div class="modal fade" id="approveTimeModal{{it.pk}}" tabindex="-1"
                                 aria-labelledby="approveTimeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h5 class="modal-title" id="approveTimeModalLabel">Approve Time</h5>
                                            <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="" method="post" id="approveTimeForm{{it.pk}}" class="form">
                                                {% csrf_token %}
                                                <input type="hidden" name="dispute_id" value="{{it.pk}}">
                                                <div class="form-group">
                                                    <div class="row row mx-2">    
                                                        <input type="number" name="approve_time" id="approve_time" placeholder="approved time" min="0" required class="form-control">
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Cancel
                                            </button>
                                            <button type="submit" form="approveTimeForm{{it.pk}}" class="btn btn-primary" name="action" value="YES">
                                                Approve
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <!-- </form> -->
                            <td>
                                <!-- Button trigger modal -->
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                    data-target="#exampleModal{{it.pk}}">
                                    <i class="fas fa-ban fa-2x"></i>
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal{{it.pk}}" tabindex="-1"
                                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h5 class="modal-title" id="exampleModalLabel">Reasons</h5>
                                            <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="" method="post" id="reasonForm{{it.pk}}" class="form">
                                                {% csrf_token %}
                                                <input type="hidden" name="dispute_id" value="{{it.pk}}">
                                                <div class="form-group">
                                                    <div class="row row mx-2">    
                                                        <textarea cols="10" rows="10" name="reasonArea" class="form-control"  placeholder="Reason for declining the agent's dispute..."></textarea>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Cancel
                                            </button>
                                            <button type="submit" form="reasonForm{{it.pk}}" class="btn btn-primary" name="action" value="NO">
                                                Send & Decline
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          
          {% if res.has_other_pages %}
             <ul class="pagination">
                {% if res.has_previous %}
                   <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);" id="{{ res.previous_page_number }}">&laquo;</a></li>
                {% else %}
                   <li class="paginate_button page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                {% endif %}
                {% for i in res.paginator.page_range %}
                   {% if res.number == i %}
                   <li class="paginate_button page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                   {% else %}
                   <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);" id="{{ i }}">{{ i }}</a></li>
                   {% endif %}
                {% endfor %}
                {% if res.has_next %}
                   <li class="paginate_button page-item"><a class="page-link" onclick="pageFilter(this.id);" id="{{ res.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="paginate_button page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                {% endif %}
             </ul>
          {% endif %}
          
          </div>
       </div>
       
    </div>
 </section>
{% endblock content %}


{% block customJs %}
<script>

    function filter(){
        let fdate = document.getElementById('fdate').value;
        let tdate = document.getElementById('tdate').value;
        const filterBtn = document.getElementById('Filter');
        filterBtn.href = "?fdate="+fdate+"&tdate="+tdate;
        filterBtn.click();
    };

    function pageFilter(id){
        let paginationLinkBtn = document.getElementById(id);
        console.log(id);
        let queryString = window.location.search;
        if (queryString !== ''){
            const urlParams = new URLSearchParams(queryString);
            if (urlParams.has("fdate") && urlParams.has("tdate")){
                if(urlParams.has("page")){
                    urlParams.set("page",id);
                }else{
                    urlParams.set("page",id);
                }
                console.log("button clicked");
                queryString = "?"+urlParams.toString();
                paginationLinkBtn.href = queryString;
                paginationLinkBtn.click();
                return true;
            }else if (urlParams.has("page")){
               urlParams.set("page",id);
               queryString = "?"+urlParams.toString();
                paginationLinkBtn.href = queryString;
                paginationLinkBtn.click();
                return true;
            }
        }else{
            paginationLinkBtn.href = "?page="+id;
            paginationLinkBtn.click();
            return true;
        }
    };

</script>
{% endblock customJs %}